//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demopractica
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказы()
        {
            this.Состав_заказа = new HashSet<Состав_заказа>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> дата_заказа { get; set; }
        public Nullable<System.DateTime> дата_доставки { get; set; }
        public Nullable<int> пункт_выдачи { get; set; }
        public Nullable<int> id_пользователя { get; set; }
        public Nullable<int> код_для_получения { get; set; }
        public string статус_заказа { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
        public virtual Пункт_выдачи Пункт_выдачи1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Состав_заказа> Состав_заказа { get; set; }
    }
}
