//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demopractica
{
    using System;
    using System.Collections.Generic;
    
    public partial class Состав_заказа
    {
        public int id_состава { get; set; }
        public int id_заказа { get; set; }
        public int id_товара { get; set; }
        public int количество_товара { get; set; }
    
        public virtual Заказы Заказы { get; set; }
        public virtual Товар_декор Товар_декор { get; set; }
    }
}
