//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demopractica
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товар_декор
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Товар_декор()
        {
            this.Состав_заказа = new HashSet<Состав_заказа>();
        }
    
        public int id { get; set; }
        public string артикул { get; set; }
        public string наименование { get; set; }
        public string единица_измерения { get; set; }
        public Nullable<double> стоимость { get; set; }
        public Nullable<double> размер_максимально_возможной_скидки { get; set; }
        public string производитель { get; set; }
        public string поставщик { get; set; }
        public int категория_товара_id { get; set; }
        public Nullable<double> действующая_скидка { get; set; }
        public Nullable<double> колво_на_складе { get; set; }
        public string описание { get; set; }
        public string изображение { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Состав_заказа> Состав_заказа { get; set; }
    }
}
